import {IPlant} from "./interfaces";

export const examplePlants: IPlant[] = [
    {
        id: Date.now(),
        name: 'Monstrea',
        description: 'Nagyon szep, levelei hasitottak',
        image: 'http://localhost:3000/images/monstrea.jpg',
        lastWatered: new Date('12/29/2020'),
        wateringCycle: 3,
        wateringDeadline: new Date('01/01/2021'),
    }, {
        id: Date.now() + 1,
        name: 'Futoka',
        description: 'Ez is szep, levelei futnak',
        image: 'http://localhost:3000/images/futoka.jpg',
        lastWatered: new Date('12/28/2020'),
        wateringCycle: 4,
        wateringDeadline: new Date('1/1/2021'),
    }, {
        id: Date.now() + 2,
        name: 'Zoldike',
        description: 'Megintcsak szep, leveleinek szele vilagos',
        image: 'http://localhost:3000/images/zoldike.jpg',
        lastWatered: new Date('12/28/2020'),
        wateringCycle: 5,
        wateringDeadline: new Date('02/02/2021'),
    }, {
        id: Date.now(),
        name: 'Monstrea',
        description: 'Nagyon szep, levelei hasitottak',
        image: 'http://localhost:3000/images/monstrea.jpg',
        lastWatered: new Date('12/29/2020'),
        wateringCycle: 3,
        wateringDeadline: new Date('01/01/2021'),
    }, {
        id: Date.now() + 3,
        name: 'Futoka',
        description: 'Ez is szep, levelei futnak',
        image: 'http://localhost:3000/images/futoka.jpg',
        lastWatered: new Date('12/28/2020'),
        wateringCycle: 4,
        wateringDeadline: new Date('1/1/2021'),
    }, {
        id: Date.now() + 4,
        name: 'Zoldike',
        description: 'Megintcsak szep, leveleinek szele vilagos',
        image: 'http://localhost:3000/images/zoldike.jpg',
        lastWatered: new Date('12/28/2020'),
        wateringCycle: 5,
        wateringDeadline: new Date('02/02/2021'),
    },{
        id: Date.now() + 5,
        name: 'Monstrea',
        description: 'Nagyon szep, levelei hasitottak',
        image: 'http://localhost:3000/images/monstrea.jpg',
        lastWatered: new Date('12/29/2020'),
        wateringCycle: 3,
        wateringDeadline: new Date('01/01/2021'),
    }, {
        id: Date.now() + 6,
        name: 'Futoka',
        description: 'Ez is szep, levelei futnak',
        image: 'http://localhost:3000/images/futoka.jpg',
        lastWatered: new Date('12/28/2020'),
        wateringCycle: 4,
        wateringDeadline: new Date('1/1/2021'),
    }, {
        id: Date.now() + 7,
        name: 'Monstrea',
        description: 'Nagyon szep, levelei hasitottak',
        image: 'http://localhost:3000/images/monstrea.jpg',
        lastWatered: new Date('12/29/2020'),
        wateringCycle: 3,
        wateringDeadline: new Date('01/01/2021'),
    }, {
        id: Date.now() + 8,
        name: 'Futoka',
        description: 'Ez is szep, levelei futnak',
        image: 'http://localhost:3000/images/futoka.jpg',
        lastWatered: new Date('12/28/2020'),
        wateringCycle: 4,
        wateringDeadline: new Date('1/1/2021'),
    }
]
